services:
  - type: web
    name: product-service
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./services/product-service/Dockerfile
    dockerContext: ./services/product-service
    healthCheckPath: /admin/health
    initialDeployHook: npm run seed
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: ENABLE_BOOTSTRAP_INGEST
        value: "false"
      - key: SEED_SOURCE_URL
        value: https://dummyjson.com/products?limit=100

  - type: web
    name: segment-service
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./services/segment-service/Dockerfile
    dockerContext: ./services/segment-service
    healthCheckPath: /segments/evaluate
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false

  - type: web
    name: frontend
    runtime: docker
    plan: free
    dockerfilePath: ./services/frontend/Dockerfile
    dockerContext: ./services/frontend
    envVars:
      - key: VITE_PRODUCTS_API
        value: https://product-service.onrender.com
      - key: VITE_SEGMENTS_API
        value: https://segment-service.onrender.com
